server:
  port: ${SERVER_PORT}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Disable since we're defining explicit routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: ["*"]
            allowedMethods: [GET, POST, PUT, DELETE, PATCH, OPTIONS]
            allowedHeaders: '*'
            allowCredentials: true
      routes: 
        # Fallback routes using Service Connect DNS
        # These will only be used if Eureka routes fail
        - id: skill-service-fallback
          uri: http://skill-service:8100
          predicates:
            - Path=/api/v1/tags/**,/api/v1/clusters/**,/api/v1/atoms/**,/api/v1/capsules/**,/api/v1/growth-tracks/**,/api/v1/talent-routes/**,/api/v1/uploads/**
          filters:
            - StripPrefix=2
        
        - id: user-management-fallback
          uri: http://user-management:8090
          predicates:
            - Path=/api/v1/auth/**,/api/v1/register/**,/api/v1/roles/**,/api/v1/users/**
        
        - id: lms-service-fallback
          uri: http://lms-service:8180
          predicates:
            - Path=/api/v1/moodle/**
          filters:
            - StripPrefix=2
        
        - id: roadmap-service-fallback
          uri: http://roadmap-service:8110
          predicates:
            - Path=/api/v1/roadmap/**,/api/v1/learner/**

eureka:
    register-with-eureka: true  # Consistent with not using Eureka for routing
    fetch-registry: false        # Don't use Eureka for routing
