server:
  port: ${SERVER_PORT}
spring:
  cloud:
    gateway:
      routes:
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/tags/**
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/clusters/**
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/atoms/**
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/capsules/**
       
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
